// <auto-generated />
using System;
using ClinicManagementSystem.DAL.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ClinicManagementSystem.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260228011833_v2")]
    partial class v2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("AppointmentDate")
                        .HasColumnType("date");

                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("DoctorId");

                    b.HasIndex("PatientId");

                    b.ToTable("Appointments");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Clinic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clinics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            City = "Port Said",
                            Name = "Port Said Medical Center",
                            Phone = "0661234567"
                        },
                        new
                        {
                            Id = 2,
                            City = "Cairo",
                            Name = "Cairo Health Clinic",
                            Phone = "0223456789"
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Doctor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ClinicId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClinicId");

                    b.ToTable("Doctors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClinicId = 1,
                            Email = "ahmed@clinic.com",
                            Name = "Dr. Ahmed Hassan",
                            Phone = "01012345678",
                            Specialization = "Cardiology"
                        },
                        new
                        {
                            Id = 2,
                            ClinicId = 1,
                            Email = "sara@clinic.com",
                            Name = "Dr. Sara Ali",
                            Phone = "01112345678",
                            Specialization = "Dermatology"
                        },
                        new
                        {
                            Id = 3,
                            ClinicId = 2,
                            Email = "mohamed@clinic.com",
                            Name = "Dr. Mohamed Tarek",
                            Phone = "01212345678",
                            Specialization = "Orthopedics"
                        },
                        new
                        {
                            Id = 4,
                            ClinicId = 2,
                            Email = "mona@clinic.com",
                            Name = "Dr. Mona Ibrahim",
                            Phone = "01512345678",
                            Specialization = "Pediatrics"
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Schedule", b =>
                {
                    b.Property<int>("DoctorId")
                        .HasColumnType("int");

                    b.Property<int>("Day")
                        .HasColumnType("int");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("DoctorId", "Day");

                    b.ToTable("Schedules");

                    b.HasData(
                        new
                        {
                            DoctorId = 1,
                            Day = 0,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 1,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 2,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 3,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 4,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 5,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 1,
                            Day = 6,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 0,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 1,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 2,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 3,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 4,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 5,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 2,
                            Day = 6,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 0,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 1,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 2,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 3,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 4,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 5,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 3,
                            Day = 6,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 0,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 1,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 2,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 3,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 4,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 5,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        },
                        new
                        {
                            DoctorId = 4,
                            Day = 6,
                            EndTime = new TimeOnly(20, 0, 0),
                            StartTime = new TimeOnly(16, 0, 0)
                        });
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Appointment", b =>
                {
                    b.HasOne("ClinicManagementSystem.DAL.Data.Models.Doctor", "Doctor")
                        .WithMany("Appointments")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ClinicManagementSystem.DAL.Data.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Doctor", b =>
                {
                    b.HasOne("ClinicManagementSystem.DAL.Data.Models.Clinic", "Clinic")
                        .WithMany("Doctors")
                        .HasForeignKey("ClinicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Clinic");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Schedule", b =>
                {
                    b.HasOne("ClinicManagementSystem.DAL.Data.Models.Doctor", "Doctor")
                        .WithMany("Schedules")
                        .HasForeignKey("DoctorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Doctor");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Clinic", b =>
                {
                    b.Navigation("Doctors");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Doctor", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("ClinicManagementSystem.DAL.Data.Models.Patient", b =>
                {
                    b.Navigation("Appointments");
                });
#pragma warning restore 612, 618
        }
    }
}
